try
	函数 1, 2, 3
catch 错误
	打印 错误

try 函数 1, 2, 3
catch 错误
	打印 错误

try
	打印 "正在try"
	函数 1, 2, 3

do
	成功, 结果 = try
		函数 1, 2, 3
	catch 错误
		打印 错误

	成功, 结果 = try 函数 1, 2, 3

try 表.函数
try 表.函数!
try 表.函数()
try (表.函数!)
try (表\函数(1, 2, 3))

try 表.函数 1
try 表.函数(1)

if (try 函数 1
catch 错误
	打印 错误)
	打印 "好的"

if try (函数 1)
catch 错误
		打印 错误
	打印 "好的"

do
	if 成功, 结果 := try 函数 "abc", 123
		打印 结果

	成功, 结果 = try 函数 "abc", 123
	catch 错误
		打印 错误

	打印 结果 if 成功, 结果 := try 函数 "abc", 123
	catch 错误
		打印 错误

do
	try
		函数 1, 2, 3

	try 函数 1, 2, 3

nil

